# Generated by Django 3.0.3 on 2020-02-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
